// <auto-generated />
namespace WebSignalR.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class VoteItem_Closed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VoteItem_Closed));
        
        string IMigrationMetadata.Id
        {
            get { return "201402261308441_VoteItem_Closed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
